import { chromium } from "playwright";
import { serve } from "./serve.mjs";
const dir = process.argv[2];
const { url, close } = await serve(dir, "/xote/");
import fs from "node:fs";
const executablePath = process.env.RESDOCS_CHROMIUM ?? (fs.existsSync("/opt/pw-browsers/chromium") ? "/opt/pw-browsers/chromium" : undefined);
const browser = await chromium.launch({ executablePath });
const page = await browser.newPage();
const errors = [];
page.on("console", m => { if (m.type() === "error") errors.push(m.text()); });
page.on("pageerror", e => errors.push(String(e)));
await page.goto(url);
await page.waitForSelector(".nav-link");
console.log("title:", await page.title());
console.log("sidebar entries:", await page.locator(".nav-link").count());
console.log("home modules:", await page.locator(".home-module").count());
await page.click('.nav-link:text-is("Xote.View")');
await page.waitForSelector("#value-eachWithKey");
console.log("url after click:", page.url());
console.log("items on View:", await page.locator(".item").count());
console.log("sub entries visible:", await page.locator(".nav-sub").count());
console.log("ref links in element sig:", await page.locator("#value-element .signature a.ref").count());
console.log("first ref href:", await page.locator("#value-element .signature a.ref").first().getAttribute("href"));
await page.click(".search-input");
await page.keyboard.type("ewk");
await page.waitForSelector(".result");
console.log("results:", await page.locator(".result").count(), "first:", await page.locator(".result-name").first().textContent());
await page.keyboard.press("ArrowDown");
await page.keyboard.press("ArrowUp");
console.log("selected:", await page.locator('.result[aria-selected="true"] .result-name').textContent());
await page.keyboard.press("Enter");
console.log("url after enter:", page.url());
console.log("results still visible:", await page.locator(".result").count());
console.log("target visible:", await page.locator("#value-eachWithKey").isVisible());
// cold deep link (served through 404.html)
await page.goto(url + "module/Xote.Router#module-Link");
await page.waitForSelector("#module-Link");
const top = await page.evaluate(() => document.getElementById("module-Link").getBoundingClientRect().top);
console.log("deep link element top after load:", Math.round(top), "url:", page.url());
console.log("doc title:", await page.title());
await page.click(".theme-toggle");
console.log("theme:", await page.evaluate(() => document.documentElement.getAttribute("data-theme")));
await page.goto(url + "module/Nope");
await page.waitForSelector(".notice");
console.log("notice:", await page.locator(".notice").textContent());
console.log("errors:", errors);
await browser.close();
close();
